### ISSUE TITLE
processes messages per queue

### ISSUE THREAD

**Issue by Notalifeform** [davydovanton/sidekiq-history#14]
Hi @davydovanton 
As discussed here https://github.com/mperham/sidekiq/issues/1626#issuecomment-99124184 I am looking for statistics about the number of messages processed per queue. Now this is only recorded for the complete sidedkiq instance. Preferably these stats should be exposed by a json API call.
Right now I created a custom sidekiq module (only a few lines) to expose the queue length and latency of all queues.  It would be great if exposing the number of messaged proccess per queue could be incorporated.

**Comment by davydovanton** [comment]
@Notalifeform hello, thank you for this issue! :green_heart: 
I think that I understood you. Also I think that it's really interesting idea. I can create page something like root page ([link](https://sidekiq-history-gem.herokuapp.com/sidekiq/history) or screenshot below) only for queue. What do you think? it's will be helpful for you?
![screenshot 2015-05-07 22 21 53](https://cloud.githubusercontent.com/assets/1147484/7523976/88cb9f88-f507-11e4-9451-8cc520d07437.jpg)

**Comment by Notalifeform** [comment]
@davydovanton I think having the information per worker would be even better than per queue - it would be a great feature for our use.  If this information would be exposed through a (stats) json api - we could also use the numbers in our monitoring system (zabbix).

**Comment by davydovanton** [comment]
yes, creation API also on my TODO list :)

**Comment by davydovanton** [comment]
@Notalifeform hello again :smiley: 
If you want to see real applications with my gem you can check [this link](http://sidekiq-history-gem.herokuapp.com/sidekiq/history). Also I added more information in worker page. As you can see on worker page you can find table with worker information per each day.  (screenshot below)
![screenshot 2015-05-11 21 42 13](https://cloud.githubusercontent.com/assets/1147484/7576137/594eaf86-f843-11e4-8e74-0f5382555d5f.jpg)

**Comment by Notalifeform** [comment]
looks nice! I'll be waching this repo to see the progress :-)

**Comment by davydovanton** [comment]
no problem :smiley_cat:
