### ISSUE TITLE
Choose date selector for gem

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/sidekiq-history#18]
I want to add date selector for worker table, charts, etc. But I have a little problem. I don't know what the best design solutions (and libraries) for this type date selectors. Now I think about slider like as [jQRangeSlider](http://ghusse.github.io/jQRangeSlider/).

Therefore it's very important for me to see your ideas and suggestions
Thanks.
/cc @mperham

**Comment by mperham** [comment]
I'm the last person to ask about specific JavaScript libraries.  In general though, avoid dependencies so stick with one that requires just jQuery.

**Comment by rgb-one** [comment]
Best is a relative term. If you can find one that satisfies your requirements adequately then work with it. Im no better off than mperham when it comes to identifying and recommending Javascript libraries but for a more informed decision you can communicate with persons with experience at channels like ##javascript or maybe navigate through some javascript powered github repositories.

**Comment by davydovanton** [comment]
Ultimately I used [jquery UI datapicker](https://api.jqueryui.com/datepicker/). 
Thank you for your replies :star2:

Gifs:
![sidekiq-history-chart](https://cloud.githubusercontent.com/assets/1147484/7599317/ab3fedca-f909-11e4-8368-006ff1bbadf0.gif)
![sidekiq-history-mobile-full-page](https://cloud.githubusercontent.com/assets/1147484/7599319/ab6f1a78-f909-11e4-911c-ab7c2d3ac5ff.gif)

**Comment by mperham** [comment]
Beautiful, love it!

**Comment by davydovanton** [comment]
thanks! :smiley:
