### ISSUE TITLE
use deprecation command

### ISSUE THREAD

**Issue by stamm** [davydovanton/sidekiq-history#21]
When I open url: sidekiq/history in my log I see:
```
Passing 'disconnect!' command to redis as is; blind passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/connection_pool-2.1.2/lib/connection_pool/timed_stack.rb:133:in `block in discard!')
```

Part of Gemfile.lock:

```
sidekiq (3.2.6)
  celluloid (= 0.15.2)
  connection_pool (>= 2.0.0)
  json
  redis (>= 3.0.6)
  redis-namespace (>= 1.3.1)
sidekiq-history (0.0.5)
  sidekiq (>= 3.0.0)
sidekiq-limit_fetch (2.2.6)
  sidekiq (>= 2.6.5, < 4.0)
sidetiq (0.6.1)
  celluloid (>= 0.14.1)
  ice_cube (~> 0.12.0)
  sidekiq (>= 2.16.0)
```

**Comment by davydovanton** [comment]
please, update your sidekiq version to [3.3.4](https://github.com/mperham/sidekiq/releases/tag/v3.3.4)

I forgot to add this to documentation :sweat:

**Comment by stamm** [comment]
I can't =(
Because sidekiq-limit_fetch has bugs with sidekiq 3.3.4, celluloid in particular

**Comment by stamm** [comment]
I think you need add sidekiq version as dependency, not only documentation

**Comment by davydovanton** [comment]
@stamm what kind of bugs sidekiq-limit_fetch has with sidekiq 3.3.4?
may be @brainopia will help to you?

**Comment by brainopia** [comment]
@stamm Hi, I had fixed compatibility with Celluloid 0.16 in March - https://github.com/brainopia/sidekiq-limit_fetch/commit/541fad464e6d9b1ddaa3f048f211e0196db8afca. And I had no complaints since. Could you upgrade sidekiq-limit_fetch and check?

**Comment by stamm** [comment]
We upgrade to latest version of sidekiq-limit_fetch, I don't remember exactly reason because we downgrade. I think that sidekiq don't stop. Do you remember, @antoshalee?

**Comment by davydovanton** [comment]
sorry, but i'll close this issue
