### ISSUE TITLE
history with multiple Worker Classes raise runtime error

### ISSUE THREAD

**Issue by nessur** [davydovanton/sidekiq-history#30]
When running more than one worker class, sidekiq-history raises `NoMethodError: undefined method `symbolize_keys' for nil:NilClass` when recording statistics. 

lib/sidekiq/history/middleware.rb:50

To reproduce: 
1. Execute jobs with SendEmailWorker one or more times
2. Executes jobs with SendTwitterWorker once
3. See 'SendTwitterWorker' fail, with the 'retries' tab in sidekiq-web, showing the error message `NoMethodError: undefined method symbolize_keys' for nil:NilClass`
4. if you execute workers with (backtrace: true), then the error is at `lib/sidekiq/history/middleware.rb:50`

**Comment by davydovanton** [comment]
Fixed this in #33

**Comment by davydovanton** [comment]
thanks!
